OnlineTraveling/src/java/models/Booking.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package models;

import java.sql.Date;

/**
 *
 * @author ACER
 */
public class Booking {

    private int BookingId;
    private int RoomId;
    private int userID;
    private int DiscountId;
    private Date ToDate;
    private Date FromDate;
    private String Status;
    private float Rating;
    private float Price;
    private String Comment;
    private String RoomName;
    private String hotelName;
    private String hotelID;
    private int RatePlanId;
    public Booking() {
    }

    public Booking(int BookingId, int RoomId, int userID, int DiscountId, Date ToDate, Date FromDate, String Status, float Rating, float Price, String RoomName, String hotelName, String hotelID) {
        this.BookingId = BookingId;
        this.RoomId = RoomId;
        this.userID = userID;
        this.DiscountId = DiscountId;
        this.ToDate = ToDate;
        this.FromDate = FromDate;
        this.Status = Status;
        this.Rating = Rating;
        this.Price = Price;
        this.RoomName = RoomName;
        this.hotelName = hotelName;
        this.hotelID = hotelID;
    }

    public Booking(int BookingId, int RoomId, int userID, int DiscountId, Date ToDate, Date FromDate, String Status, float Rating, float Price, String RoomName, String hotelName) {
        this.BookingId = BookingId;
        this.RoomId = RoomId;
        this.userID = userID;
        this.DiscountId = DiscountId;
        this.ToDate = ToDate;
        this.FromDate = FromDate;
        this.Status = Status;
        this.Rating = Rating;
        this.Price = Price;
        this.RoomName = RoomName;
        this.hotelName = hotelName;
    }



    public Booking(int BookingId, int RoomId, int userID, int DiscountId, Date ToDate, Date FromDate, String Status, float Rating, float Price, String RoomName) {
        this.BookingId = BookingId;
        this.RoomId = RoomId;
        this.userID = userID;
        this.DiscountId = DiscountId;
        this.ToDate = ToDate;
        this.FromDate = FromDate;
        this.Status = Status;
        this.Rating = Rating;
        this.Price = Price;
        this.RoomName = RoomName;
    }

    public Booking(int BookingId, int RoomId, int userID, int DiscountId, Date ToDate, Date FromDate, String Status, float Price, String RoomName, String hotelName, String hotelID) {
        this.BookingId = BookingId;
        this.RoomId = RoomId;
        this.userID = userID;
        this.DiscountId = DiscountId;
        this.ToDate = ToDate;
        this.FromDate = FromDate;
        this.Status = Status;
        this.Price = Price;
        this.RoomName = RoomName;
        this.hotelName = hotelName;
        this.hotelID = hotelID;
    }
   
    public String getComment() {
        return Comment;
    }

    public void setComment(String Comment) {
        this.Comment = Comment;
    }

    public String getHotelName() {
        return hotelName;
    }

    public void setHotelName(String hotelName) {
        this.hotelName = hotelName;
    }

    public String getHotelID() {
        return hotelID;
    }

    public void setHotelID(String hotelID) {
        this.hotelID = hotelID;
    }



    public int getBookingId() {
        return BookingId;
    }

    public void setBookingId(int BookingId) {
        this.BookingId = BookingId;
    }

    public int getRoomId() {
        return RoomId;
    }

    public void setRoomId(int RoomId) {
        this.RoomId = RoomId;
    }

    public int getUserID() {
        return userID;
    }

    public void setUserID(int userID) {
        this.userID = userID;
    }

    public int getDiscountId() {
        return DiscountId;
    }

    public void setDiscountId(int DiscountId) {
        this.DiscountId = DiscountId;
    }

    public Date getToDate() {
        return ToDate;
    }

    public void setToDate(Date ToDate) {
        this.ToDate = ToDate;
    }

    public Date getFromDate() {
        return FromDate;
    }

    public void setFromDate(Date FromDate) {
        this.FromDate = FromDate;
    }

    public String getStatus() {
        return Status;
    }

    public void setStatus(String Status) {
        this.Status = Status;
    }

    public float getRating() {
        return Rating;
    }

    public void setRating(float Rating) {
        this.Rating = Rating;
    }

    public float getPrice() {
        return Price;
    }

    public void setPrice(float Price) {
        this.Price = Price;
    }

    public String getRoomName() {
        return RoomName;
    }

    public void setRoomName(String RoomName) {
        this.RoomName = RoomName;
    }

    @Override
    public String toString() {
        return "Booking{" + "BookingId=" + BookingId + ", RoomId=" + RoomId + ", userID=" + userID + ", DiscountId=" + DiscountId + ", ToDate=" + ToDate + ", FromDate=" + FromDate + ", Status=" + Status + ", Rating=" + Rating + ", Price=" + Price + ", RoomName=" + RoomName + '}';
    }
}

OnlineTraveling/src/java/models/Hotel.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package models;

import java.util.ArrayList;

/**
 *
 * @author admin
 */
public class Hotel {

    private int HotelId;
    private String HotelName;
    private String HotelAddress;
    private String Description;
    private String HotelImage;
    private int busiID;
    private int DestinationID;
    ArrayList<RoomType> rooms;
    private float avgRating;

    public Hotel() {
    }

    public Hotel(int HotelId, String HotelName, String HotelAddress, String Description, String HotelImage, int busiID, int DestinationID) {
        this.HotelId = HotelId;
        this.HotelName = HotelName;
        this.HotelAddress = HotelAddress;
        this.Description = Description;
        this.HotelImage = HotelImage;
        this.busiID = busiID;
        this.DestinationID = DestinationID;
    }

    public Hotel(int HotelId, String HotelName, String HotelAddress, String Description, String HotelImage, int busiID, int DestinationID, ArrayList<RoomType> rooms) {
        this.HotelId = HotelId;
        this.HotelName = HotelName;
        this.HotelAddress = HotelAddress;
        this.Description = Description;
        this.HotelImage = HotelImage;
        this.busiID = busiID;
        this.DestinationID = DestinationID;
        this.rooms = rooms;
    }

    public Hotel(int HotelId, String HotelName, String HotelAddress, String Description, String HotelImage, int busiID, int DestinationID, ArrayList<RoomType> rooms, float avgRating) {
        this.HotelId = HotelId;
        this.HotelName = HotelName;
        this.HotelAddress = HotelAddress;
        this.Description = Description;
        this.HotelImage = HotelImage;
        this.busiID = busiID;
        this.DestinationID = DestinationID;
        this.rooms = rooms;
        this.avgRating = avgRating;
    }

    public int getHotelId() {
        return HotelId;
    }

    public void setHotelId(int HotelId) {
        this.HotelId = HotelId;
    }

    public String getHotelName() {
        return HotelName;
    }

    public void setHotelName(String HotelName) {
        this.HotelName = HotelName;
    }

    public String getHotelAddress() {
        return HotelAddress;
    }

    public void setHotelAddress(String HotelAddress) {
        this.HotelAddress = HotelAddress;
    }

    public String getDescription() {
        return Description;
    }

    public void setDescription(String Description) {
        this.Description = Description;
    }

    public String getHotelImage() {
        return HotelImage;
    }

    public void setHotelImage(String HotelImage) {
        this.HotelImage = HotelImage;
    }

    public int getBusiID() {
        return busiID;
    }

    public void setBusiID(int busiID) {
        this.busiID = busiID;
    }

    public int getDestinationID() {
        return DestinationID;
    }

    public void setDestinationID(int DestinationID) {
        this.DestinationID = DestinationID;
    }

    public ArrayList<RoomType> getRooms() {
        return rooms;
    }

    public void setRooms(ArrayList<RoomType> rooms) {
        this.rooms = rooms;
    }

    public float getAvgRating() {
        return avgRating;
    }

    public void setAvgRating(float avgRating) {
        this.avgRating = avgRating;
    }

    @Override
    public String toString() {
        return "Hotel{" + "HotelId=" + HotelId + ", HotelName=" + HotelName + ", HotelAddress=" + HotelAddress + ", Description=" + Description + ", HotelImage=" + HotelImage + ", busiID=" + busiID + ", DestinationID=" + DestinationID + ", rooms=" + rooms + '}';
    }

}

OnlineTraveling/src/java/models/Room.java
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package models;

/**
 *
 * @author HONG QUAN
 */
public class Room {

    private int RoomId;
    private String RoomName;
    private String RoomDescription;
    private String RoomImage;
    private int Price;
    private float Size;
    private int Quantity;
    private RoomType roomType;
    private Hotel hotel;
    private int available;
    private float avgRating;
    private int amount;
    private float manyNightPrice;
    private String oneNightPrice_str;//Only for booking confirmation page, for storing the price of 1 room for 1 night
    private String manyNightPrice_str;//Only for booking confirmation page, for storing the price of 1 room for many night
    private String oneRoomPrice_str;//Only for booking confirmation page, for storing the price of many room for many night
    private int availablePlan; //Storing how many available plan for a room in hotel details page
    private int PlanId; // Holding value rate plan value for booking confirmation page.

    public int getRoomId() {
        return RoomId;
    }

    public void setRoomId(int RoomId) {
        this.RoomId = RoomId;
    }

    public String getRoomName() {
        return RoomName;
    }

    public void setRoomName(String RoomName) {
        this.RoomName = RoomName;
    }

    public Room() {
    }

    public String getRoomDescription() {
        return RoomDescription;
    }

    public void setRoomDescription(String RoomDescription) {
        this.RoomDescription = RoomDescription;
    }

    public String getRoomImage() {
        return RoomImage;
    }

    public void setRoomImage(String RoomImage) {
        this.RoomImage = RoomImage;
    }

    public int getPrice() {
        return Price;
    }

    public void setPrice(int Price) {
        this.Price = Price;
    }

    public float getSize() {
        return Size;
    }

    public void setSize(float Size) {
        this.Size = Size;
    }

    public int getQuantity() {
        return Quantity;
    }

    public void setQuantity(int Quantity) {
        this.Quantity = Quantity;
    }

    public RoomType getRoomType() {
        return roomType;
    }

    public void setRoomType(RoomType roomType) {
        this.roomType = roomType;
    }

    public Hotel getHotel() {
        return hotel;
    }

    public void setHotel(Hotel hotel) {
        this.hotel = hotel;
    }

    public int getAvailable() {
        return available;
    }

    public void setAvailable(int available) {
        this.available = available;
    }

    public float getAvgRating() {
        return avgRating;
    }

    public void setAvgRating(float avgRating) {
        this.avgRating = avgRating;
    }

    public int getAmount() {
        return amount;
    }

    public void setAmount(int amount) {
        this.amount = amount;
    }

    public String getOneNightPrice_str() {
        return oneNightPrice_str;
    }

    public void setOneNightPrice_str(String oneNightPrice_str) {
        this.oneNightPrice_str = oneNightPrice_str;
    }

    public int getAvailablePlan() {
        return availablePlan;
    }

    public void setAvailablePlan(int availablePlan) {
        this.availablePlan = availablePlan;
    }

    public int getPlanId() {
        return PlanId;
    }

    public void setPlanId(int PlanId) {
        this.PlanId = PlanId;
    }

    public String getManyNightPrice_str() {
        return manyNightPrice_str;
    }

    public void setManyNightPrice_str(String manyNightPrice_str) {
        this.manyNightPrice_str = manyNightPrice_str;
    }

    public String getOneRoomPrice_str() {
        return oneRoomPrice_str;
    }

    public void setOneRoomPrice_str(String oneRoomPrice_str) {
        this.oneRoomPrice_str = oneRoomPrice_str;
    }

    public float getManyNightPrice() {
        return manyNightPrice;
    }

    public void setManyNightPrice(float manyNightPrice) {
        this.manyNightPrice = manyNightPrice;
    }

    public Room(int RoomId, String RoomName, String RoomDescription, String RoomImage, int Price, float Size, int Quantity, RoomType roomType, Hotel hotel, int available) {
        this.RoomId = RoomId;
        this.RoomName = RoomName;
        this.RoomDescription = RoomDescription;
        this.RoomImage = RoomImage;
        this.Price = Price;
        this.Size = Size;
        this.Quantity = Quantity;
        this.roomType = roomType;
        this.hotel = hotel;
        this.available = available;
    }

    public Room(int RoomId, String RoomName, String RoomDescription, String RoomImage, int Price, float Size, int Quantity, RoomType roomType, Hotel hotel, int available, float avgRating) {
        this.RoomId = RoomId;
        this.RoomName = RoomName;
        this.RoomDescription = RoomDescription;
        this.RoomImage = RoomImage;
        this.Price = Price;
        this.Size = Size;
        this.Quantity = Quantity;
        this.roomType = roomType;
        this.hotel = hotel;
        this.available = available;
        this.avgRating = avgRating;
    }

    @Override
    public String toString() {
        return "Room{" + "RoomId=" + RoomId + ", RoomName=" + RoomName + ", RoomDescription=" + RoomDescription + ", RoomImage=" + RoomImage + ", Price=" + Price + ", Size=" + Size + ", Quantity=" + Quantity + ", roomType=" + roomType + ", hotel=" + hotel + '}';
    }

}

OnlineTraveling/web/Admin.jsp
<%-- 
    Document   : Admin.jsp
    Created on : Sep 13, 2022, 10:01:19 PM
    Author     : admin
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
    </head>
    <body>
        <h1>Hello World!</h1>
    </body>
</html>

OnlineTraveling/web/ListHotel.jsp
<%-- Document : ListHotel Created on : Sep 30, 2022, 10:06:56 PM Author : HONG QUAN --%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@page contentType="text/html" pageEncoding="UTF-8" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<!DOCTYPE html>
<html>

    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Hotel List</title>
        <link rel="stylesheet" href="CSS/rentailHistory.css" />
        <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    </head>

    <body>
        <%@include file="View/Header.jsp" %>
        <c:if test="${requestScope.listHo == null}">
            <h2>${requestScope.error}</h2>
        </c:if>
        <c:if test="${requestScope.listHo != null}">
            <div class="container">
                <div class ="row">
                    <div class="col-md-2">
                        </br></br></br></br></br></br></br></br></br>                                    
                        <form action="hotel" method="post">
                            <c:if test="${sessionScope.fromDate != null}">
                                <h2>Theo giá</h2>
                                <label for="price1">VND 0 - VND 1.000.000</label>
                                <input type="checkbox" id="price1" name="price1" value="price1">
                                <label for="price2">VND 1.000.000 - VND 2.000.000</label>
                                <input type="checkbox" id="price2" name="price2" value="price2">
                                <label for="price3">VND 2.000.000 - VND 3.000.000</label>
                                <input type="checkbox" id="price3" name="price3" value="price3">
                                <label for="price4">VND 3.000.000 - VND 4.000.000</label>
                                <input type="checkbox" id="price4" name="price4" value="price4">
                                <label for="price5">VND 4.000.000+</label>
                                <input type="checkbox" id="price5" name="price5" value="price5">
                            </c:if>
                            <br/><br/>
                            <h2>Tiện nghi</h2>
                            <label for="1">Wi-fi miễn phí</label>
                            <input type="checkbox" id="1" name="1" value="1"><br/>
                            <label for="2">Chỗ để xe</label>
                            <input type="checkbox" id="2" name="2" value="2"><br/>
                            <label for="3">Phòng gia đình</label>
                            <input type="checkbox" id="3" name="3" value="3"><br/>
                            <label for="4">Lễ tân 24/7</label>
                            <input type="checkbox" id="4" name="4" value="4"><br/>
                            <label for="5">Nhà hàng</label>
                            <input type="checkbox" id="5" name="5" value="5"><br/>
                            <label for="6">Hồ bơi</label>
                            <input type="checkbox" id="6" name="6" value="6"><br/>
                            <label for="7">Cho phép vật nuôi</label>
                            <input type="checkbox" id="7" name="7" value="7">
                            <br/><br/>
                            <h2>Tiện nghi phòng</h2>
                            <label for="ra1">Bồn tắm</label>
                            <input type="checkbox" id="ra1" name="ra1" value="1"><br/>
                            <label for="ra2">Điều hòa không khí</label>
                            <input type="checkbox" id="ra2" name="ra2" value="2"><br/>
                            <label for="ra3">Phòng tắm riêng</label>
                            <input type="checkbox" id="ra3" name="ra3" value="3"><br/>
                            <label for="ra4">Ban công</label>
                            <input type="checkbox" id="ra4" name="ra4" value="4"><br/>
                            <label for="ra5">Máy giặt</label>
                            <input type="checkbox" id="ra5" name="ra5" value="5"><br/>
                            <label for="ra6">Hệ thống cách ấm</label>
                            <input type="checkbox" id="ra6" name="ra6" value="6"><br/>
                            <label for="ra7">TV màn hình phẳng</label>
                            <input type="checkbox" id="ra7" name="ra7" value="7">
                            <br/>
                            <input type="hidden" name="destination" value="${sessionScope.destinationID}">
                            <input type="submit" value="Search">
                        </form>
                    </div>
                    <div class="main col-md-10">
                        <div class="container light-style flex-grow-1 container-p-y">
                            <div id="wrapper">
                                <h1>Danh sách khách sạn</h1>
                                <table id="keywords" cellspacing="0" cellpadding="0">
                                    <thead>
                                        <tr>
                                            <th><span>View</span></th>
                                            <th><span>Name</span></th>
                                            <th><span>Address</span></th>
                                            <th><span>Description</span></th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <c:forEach items="${requestScope.listHo}" var="li">
                                            <tr>
                                                <td class="img-border">
                                                    <div><img src="${li.getHotelImage()}" alt="alt" /></div>
                                                </td>
                                                <td><a class="link" href="/OnlineTraveling/hotelDetail?hotelId=${li.getHotelId()}">${li.getHotelName()}</a>
                                                </td>
                                                <td>${li.getHotelAddress()}</td>
                                                <td>${li.getDescription()}</td>
                                            </tr>
                                        </c:forEach>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>

                </div>    
            </div>    
        </c:if>
        <%@include file="View/Footer.jsp" %>
    </body>

</html>

OnlineTraveling/web/UpdateCustomPlan.jsp
<%-- 
    Document   : UpdateCustomPlan
    Created on : Oct 31, 2022, 8:46:36 AM
    Author     : ACER
--%>

<%-- 
    Document   : UpdateFirstBookPlan
    Created on : Oct 31, 2022, 7:18:06 AM
    Author     : ACER
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
        <link rel="stylesheet" href="CSS/addNewFirstBookPlan.css">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    </head>
    <body>
        <%@include  file="View/Header.jsp" %>




    <c:if test="${requestScope.hotel.busiID != sessionScope.busiID}">
        <br><br><br><br><br><br><br><br><br><br><br><br><br>
        <h1>Bạn không có quyền truy cập vào trang này</h1>
    </c:if>
    <c:if test="${requestScope.hotel.busiID == sessionScope.busiID}">
        <c:set var="p" value="${requestScope.plan}"/>
        <p>busiID của hotel = ${requestScope.hotel.busiID}</p>
        <p>busiID của session = ${sessionScope.busiID}</p>
        <br><br><br><br><br><br><br><br><br><br><br><br><br><br>

        <div class="container-md">
            <h1>Chỉnh sửa gói giá tiêu chuấn cho khách sạn của bạn</h1>
            <div class="row">
                <div class="col-md-8">
                    <form action="updateCustomPlan" method="post">
                        <div class="">
                            <div><input class="form-control" type="text" placeholder="Tên gói giá trị" name="planName"}" required value="${p.planName}"></div>
                            <div><input type="number" min="0" max="100" class="form-control" placeholder="Phần trăm giảm giá" name="percentage" required value="${p.percentage}"></div>
                            <div>
                                <span>Phương thức thanh toán: </span>
                                <input type="radio" name="availablePayment" value="1" <c:if test="${p.availablePayment == 1}">checked</c:if>>  Tiền mặt
                                <input type="radio" name="availablePayment" value="2" <c:if test="${p.availablePayment == 2}">checked</c:if>>  Paypal
                                <input type="radio" name="availablePayment" value="3" <c:if test="${p.availablePayment == 3}">checked</c:if>>  Cả tiền mặt và paypal
                            </div>
                            <div>
                                <span>Chính sách hủy phòng:</span>
                                <input type="radio" name="cancellationPolicy" value="Non-refundable" <c:if test="${p.cancellationPolicy == 'Non-refundable'}"> checked</c:if> >  Không hoàn tiền
                                <input type="radio" name="cancellationPolicy" value="Flexible" <c:if test="${p.cancellationPolicy == 'Flexible'}"> checked</c:if>>  Theo chính sách

                            </div>
                            <div>
                                <span>Bao gồm bữa sáng:</span>
                                <input type="radio" name="meal" value="false" <c:if test="${p.meal == false}"> checked</c:if> >  Không
                                <input type="radio" name="meal" value="true" <c:if test="${p.meal == true}"> checked</c:if> >  Có

                            </div>
                        </div>
                        <input type="hidden" value="${requestScope.hotel.hotelId}" name="hotelId">
                        <input type="hidden" value="${p.planId}" name="planId">
                        <button type="submit" class="btn btn-warning">GỬI</button>

                    </form>
                </div>
            </div>
        </div>
    </c:if>

    <%@include  file="View/Footer.jsp" %>

</body>
</html>

OnlineTraveling/web/UpdateLongStayPlan.jsp
<%-- 
    Document   : UpdateLongStayPlan
    Created on : Oct 17, 2022, 5:32:18 AM
    Author     : ACER
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>JSP Page</title>
        <link rel="stylesheet" href="CSS/addNewFirstBookPlan.css">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    </head>
    <body>
        <%@include  file="View/Header.jsp" %>




        <c:if test="${requestScope.hotel.busiID != sessionScope.busiID}">
            <br><br><br><br><br><br><br><br><br><br><br><br><br>
            <h1>Bạn không có quyền truy cập vào trang này</h1>
        </c:if>
        <c:if test="${requestScope.hotel.busiID == sessionScope.busiID}">
            <c:set var="p" value="${requestScope.plan}"/>
            <br><br><br><br><br><br><br><br><br><br><br><br><br><br>

            <div class="container-md">
                <h1 style="font-weight: bold">Chỉnh sửa gói giá theo số ngày ở cho khách sạn của bạn</h1>
                <div class="row">
                    <div class="col-md-8">
                        <form action="updateLongStayPlan" method="post">
                            <div>
                                <h3>Tên gói giá trị:</h3>
                            </div>
                            <div class="form-group">
                                <input type="text" class="form-control" placeholder="Tên gói giá trị của bạn ..." name="planName" value="${requestScope.plan.planName}">
                            </div>
                            <br>

                            <div>
                                <h3>Số ngày mà khách hàng cần ở tối thiểu, cần thiết để được hưởng giá ưu đãi.</h3>
                            </div>
                            <div class="form-group">
                                <input type="number" min="1" max="730" class="form-control" placeholder="Số ngày ở" name="day" value="${requestScope.plan.day}">
                            </div>
                            <br>

                            <div>
                                <h3>Phần trăm ưu đãi mà khách hàng sẽ hưởng khi số ngày ở được đáp ứng</h3>
                            </div>
                            <br>

                            <div class="form-group">
                                <input type="number" min="0" max="100" class="form-control" placeholder="Phần trăm giảm giá" name="percentage" value="${requestScope.plan.percentage}">
                            </div>

                            <br>
                            <div>
                                <span>Phương thức thanh toán: </span>
                                <input type="radio" name="availablePayment" value="1" <c:if test="${p.availablePayment == 1}">checked</c:if>>  Tiền mặt
                                <input type="radio" name="availablePayment" value="2" <c:if test="${p.availablePayment == 2}">checked</c:if>>  Paypal
                                <input type="radio" name="availablePayment" value="3" <c:if test="${p.availablePayment == 3}">checked</c:if>>  Cả tiền mặt và paypal
                                </div>
                                <div>
                                    <span>Chính sách hủy phòng:</span>
                                    <input type="radio" name="cancellationPolicy" value="Non-refundable" <c:if test="${p.cancellationPolicy == 'Non-refundable'}"> checked</c:if> >  Không hoàn tiền
                                <input type="radio" name="cancellationPolicy" value="Flexible" <c:if test="${p.cancellationPolicy == 'Flexible'}"> checked</c:if>>  Theo chính sách

                                </div>
                                <div>
                                    <span>Bao gồm bữa sáng:</span>
                                    <input type="radio" name="meal" value="false" <c:if test="${p.meal == false}"> checked</c:if> >  Không
                                <input type="radio" name="meal" value="true" <c:if test="${p.meal == true}"> checked</c:if> >  Có

                                </div>
                        </div>
                    <input type="hidden" value="${requestScope.plan.planId}" name="PlanId">
                    <input type="hidden" value="${requestScope.hotel.hotelId}" name="HotelId">
                    <c:if test="${requestScope.error != null}">
                        <h3>${requestScope.error}</h3>
                    </c:if>
                    <button type="submit" class="btn btn-warning">GỬI</button>

                    </form>
                </div>
            </div>
        </div>
    </c:if>



    <%@include  file="View/Footer.jsp" %>